### ISSUE TITLE
Allow publishing patch releases from a release branch

### ISSUE THREAD

**Issue by Swatinem** [getsentry/craft#122]
Right now craft assumes that all your development happens on master.
However sometimes you want to do feature development on master but still keep a previous release branch around to do point releases that don’t have breaking changes.

Right now I have would suggest `releases/0.$N.x`, or `releases/$N.x` as branch names.

Maybe related to #34

**Comment by st0012** [comment]
I really hope we can add this flexibility. I maintain [sentry-ruby](https://github.com/getsentry/sentry-ruby) and I think this is particularly needed for us right now, as the team and I are still exploring the right way to implement the tracing features. 

Right now I have to stack up several PRs (8 for now) for the next minor release, which have different conflicts with each other. But I just can't merge and fix them yet. Because once I merged any one of them, I'd need to make sure the minor version can be released ASAP. Otherwise, I wouldn't be able to make any patch release until then.

At least in my case, the "must release from master" rule prolongs the development cycle and adds unnecessary pressure to me. So it'd be really great if we can allow non-master branch release.

**Comment by BYK** [comment]
Craft allows using a `--rev` argument for the `publish` command to use a different branch to publish. This assumes the necessary preparations are already done though (changelog, version bumping etc.). Would this be sufficient or useful? If so we may look into adding support for this argument in our `getsentry/publish` flow.

**Comment by st0012** [comment]
@BYK thanks for the quick response! I don't have the permission to use the `publish` command. But I think a key feature would be to merge the release branch back to the one specified in `--rev` instead of master. If the option can do that as well, I think it'd be helpful.

My above comment was mainly about the `prepare` command. And I just found that the `--no-git-checks` seems to skip the branch check. But the [release action](https://github.com/getsentry/action-prepare-release/blob/main/action.yml) doesn't seem to support that (the `force` option only skips GH's release blockers). So I guess that's the main blocker to me now. Should I open another issue in the action repo?

**Comment by BYK** [comment]
@st0012 no need for that. I'll need to think about how to streamline this process. Will be following up on here. Thanks for all the input!

>I don't have the permission to use the publish command.

You still can (and do 😃) request a publish where we can add the branch to publish from through the release action. I'll think on this too.

**Comment by chadwhitacre** [comment]
@jean85 and @ste93cry have similar needs for `sentry-symfony`, which is currently maintaining multiple major versions.

**Comment by Jean85** [comment]
I would also add that releasing on branches could also be mandatory if you need to release a (security?) patch for older versions; so it's really needed.

**Comment by chadwhitacre** [comment]
The default branch limitation also makes it difficult to test out craft locally without impacting the remote, especially given the failure on unpushed changes.

```
$ craft prepare 0.4.1            
ℹ info "craft" version is compatible with the minimal version from the configuration file.
ℹ info Checking the local repository status...
✖ error Error: Your repository has unpushed changes: the current branch is 1 commits ahead.
  at xn (/Users/chadwhitacre/.config/yarn/global/node_modules/@sentry/craft/dist/craft:606:1068)
  at Kls (/Users/chadwhitacre/.config/yarn/global/node_modules/@sentry/craft/dist/craft:639:1796)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async $Jt (/Users/chadwhitacre/.config/yarn/global/node_modules/@sentry/craft/dist/craft:643:484)
  at async Object.Zls [as handler] (/Users/chadwhitacre/.config/yarn/global/node_modules/@sentry/craft/dist/craft:643:1210)
$
```

**Comment by st0012** [comment]
@BYK thank you for implementing this 😄
