### ISSUE TITLE
`upm` target failed

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/craft#371]
https://github.com/getsentry/publish/issues/935#issuecomment-1073021905

```
[info] [[target/upm]] Cloning https://github.com/getsentry/unity/ to /tmp/_craft-release-upm-Cc9yTi...
[info] [[target/upm]] Clearing the repository.
[info] [[target/upm]] Extracting "package-release.zip".
[info] [[target/upm]] Adding files to repository.
Error:  Commit on target repository failed. Maybe there were no changes at all?
  at /usr/local/bin/craft:689:3195
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async Si (/usr/local/bin/craft:632:594)
  at async dJ.publish (/usr/local/bin/craft:689:2804)
  at async VJt (/usr/local/bin/craft:692:4672)
  at async /usr/local/bin/craft:695:89
  at async Si (/usr/local/bin/craft:632:594)
  at async l9e (/usr/local/bin/craft:695:29)
  at async Object.EJ [as handler] (/usr/local/bin/craft:697:73)
```

Perhaps due to a retry? It timed out on the first run, so it probably already did the push. On the retry, it didn't handle the fact there were no changes to push.

**Comment by kamilogorek** [comment]
It failed because the initial publish attempt released `upm` correctly - https://github.com/getsentry/publish/runs/5604762485?check_suite_focus=true

![image](https://user-images.githubusercontent.com/1523305/159265581-bc91885d-b7b0-4f96-bb6e-0e0497f39bdf.png)

Consecutive runs should exclude it from the workflow, however, because a whole action timed-out, never triggered a `failure` state (note that timeouts are not "failed" runs per-so).

The original issue, as in `upm failed` is therefore not valid.

**Comment by bruno-garcia** [comment]
The release hanged for hours. It wasn't just a short timeout. Feel free to reword the issue as u prefer.
